# Generated by Django 3.0.3 on 2025-04-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='Food',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='items',
        ),
    ]
